language: java
before_script:
  - sudo apt-get install nsis
  - export VERSION=`cat pom.xml|grep -e '<version>\(.*\)</version>'|head -n 1|sed  's/^.*<version>\(.*\)<\/version>/\1/g'`
  - echo $VERSION
script:
  - mvn clean install
after_success:
  - mvn clean deploy  --settings support/settings.xml
